# Generated by Django 2.1.5 on 2019-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190108_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=2),
        ),
    ]
