# Generated by Django 2.0.10 on 2019-01-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_productimgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImgs',
            new_name='ProductAlbum',
        ),
    ]
