# Generated by Django 2.1.5 on 2019-01-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190128_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
