# Generated by Django 2.1.5 on 2019-01-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190128_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Deleted'), ('1', 'Available'), ('2', 'Sold')], default='1', max_length=2),
        ),
    ]
