# Generated by Django 2.1.5 on 2019-01-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190128_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.CharField(max_length=100)),
                ('stock_total', models.PositiveIntegerField(default=1)),
                ('stock_on_hand', models.PositiveIntegerField(default=models.PositiveIntegerField(default=1))),
                ('status', models.CharField(choices=[('0', 'Deleted'), ('1', 'Available'), ('2', 'Sold')], default='1', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Product')),
            ],
        ),
    ]
