# Generated by Django 2.1.5 on 2019-01-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_on_hand',
            field=models.PositiveIntegerField(),
        ),
    ]
