# Generated by Django 2.1.5 on 2019-01-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190128_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_on_hand',
        ),
    ]
