# Generated by Django 2.1.5 on 2019-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20190201_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalbum',
            name='image',
            field=models.ImageField(default='no-thumb.png', upload_to='product_images/'),
        ),
    ]
