# Generated by Django 2.0.10 on 2019-01-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190116_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
