# Generated by Django 2.0.10 on 2019-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190116_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='no',
            field=models.CharField(default='Trans01', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('0', 'Sold'), ('1', 'Pending'), ('2', 'Available'), ('3', 'Deleted')], default='2', max_length=2),
        ),
    ]
