# Generated by Django 2.0.10 on 2019-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190116_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='no',
            field=models.CharField(max_length=100),
        ),
    ]
