# Generated by Django 2.0.10 on 2019-01-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20190116_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='no',
            field=models.CharField(default='Payment01', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('0', 'Sold'), ('1', 'Pending'), ('2', 'Available')], default='2', max_length=2),
        ),
    ]
