# Generated by Django 2.0.10 on 2019-01-17 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0007_auto_20190116_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='buyer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='no',
            field=models.CharField(max_length=100),
        ),
    ]
