# Generated by Django 2.0.10 on 2019-01-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20190117_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Acttive')], default='1', max_length=2),
        ),
    ]
