# Generated by Django 2.0.10 on 2019-01-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=2),
        ),
    ]
